### ISSUE TITLE
Not Working

### ISSUE THREAD

**Issue by mdnbras** [claudsonm/cep-promise-php#5]
Usando o mesmo CEP do exemplo e não está funcionando a consulta. Help!

**Comment by claudsonm** [comment]
Instalei o pacote e fiz a chamada. Está normal.

![image](https://user-images.githubusercontent.com/4139808/82696969-7e5ab280-9c3e-11ea-8d87-6c375eb70e4a.png)

**Comment by mdnbras** [comment]
Meu pacote guzzlehttp/promise estava em uma versão anterior instalada pelo Slim. Então dava erro lá dentro e sempre dava que o CEP não foi encontrado. Obrigado pelo feedback!
